# Generated by Django 5.2.7 on 2025-10-21 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_coupon_order_discount_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='manual_release',
            field=models.BooleanField(default=False, verbose_name='Liberação Manual'),
        ),
        migrations.AddField(
            model_name='order',
            name='release_image',
            field=models.ImageField(blank=True, null=True, upload_to='orders/release_images/', verbose_name='Comprovante da Liberação'),
        ),
        migrations.AddField(
            model_name='order',
            name='release_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo da Liberação Manual'),
        ),
        migrations.AddField(
            model_name='order',
            name='released_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Liberado em'),
        ),
        migrations.AddField(
            model_name='order',
            name='released_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_orders', to=settings.AUTH_USER_MODEL, verbose_name='Liberado por'),
        ),
    ]
